In [1]:
import pandas as pd
data = pd.read_csv('Flow.csv')

In [2]:
data.head()

,t,x,y,u,v,p,dudx,dudy,dvdx,dvdy,dudt,dvdt,flow_type,sample_id
0,0.022222,0.368421,0.088889,0.393358,0.001115,-2.953893,0.152946,-31.138013,0.030149,-0.082668,-0.820783,0.018075,laminar,63
1,0.100000,0.315789,0.077778,0.694818,-0.001654,-2.531341,-0.100485,-21.879110,-0.007235,0.056004,-0.027166,-0.151602,laminar,77
2,0.033333,0.263158,0.022222,0.704109,-0.000018,-2.103342,0.178065,23.040452,0.022634,0.011209,0.343724,-0.002956,laminar,67
3,0.100000,0.052632,0.044444,1.002908,-0.001317,-0.410112,-0.151426,4.189388,-0.037293,-0.000843,1.339783,-0.056770,laminar,52
4,0.011111,0.789474,0.100000,-0.010775,-0.002226,-6.315435,0.000000,0.000000,0.000000,0.000000,0.179054,0.061017,laminar,62

In [3]:
len(data)

10000

In [4]:
data["flow_type"].unique()

<StringArray>
['laminar', 'turbulent']
Length: 2, dtype: str

In [5]:
data_laminar = data[data["flow_type"] == "laminar"]

In [6]:
len(data_laminar)

5000

In [7]:
data_turbulent = data[data['flow_type'] == "turbulent"]
data_turbulent.head()

,t,x,y,u,v,p,dudx,dudy,dvdx,dvdy,dudt,dvdt,flow_type,sample_id
5000,0.100000,0.789474,0.088889,1.026712,0.397843,-0.591745,3.612397,-16.325661,2.214610,-0.576598,4.703211,1.143310,turbulent,160
5001,0.044444,0.315789,0.077778,0.556785,0.064779,-0.141264,-4.962022,-16.182555,-3.764561,2.288760,7.204553,7.237551,turbulent,172
5002,0.100000,0.684211,0.022222,0.902449,0.001249,-0.474272,2.077224,-1.788085,3.266051,0.896039,-8.693098,-2.820684,turbulent,166
5003,0.088889,0.473684,0.044444,0.846398,-0.070730,-0.399574,2.375436,1.094349,-0.982396,2.121602,2.310548,0.393388,turbulent,151
5004,0.100000,0.368421,0.100000,-0.119631,-0.240132,-0.031333,0.000000,0.000000,0.000000,0.000000,6.129408,-6.712281,turbulent,159

In [8]:
data_laminar.to_csv("Laminar_dataset.csv")

In [9]:
data_turbulent.to_csv("Turbulent_dataset.csv")

In [10]:
data_laminar.head()

,t,x,y,u,v,p,dudx,dudy,dvdx,dvdy,dudt,dvdt,flow_type,sample_id
0,0.022222,0.368421,0.088889,0.393358,0.001115,-2.953893,0.152946,-31.138013,0.030149,-0.082668,-0.820783,0.018075,laminar,63
1,0.100000,0.315789,0.077778,0.694818,-0.001654,-2.531341,-0.100485,-21.879110,-0.007235,0.056004,-0.027166,-0.151602,laminar,77
2,0.033333,0.263158,0.022222,0.704109,-0.000018,-2.103342,0.178065,23.040452,0.022634,0.011209,0.343724,-0.002956,laminar,67
3,0.100000,0.052632,0.044444,1.002908,-0.001317,-0.410112,-0.151426,4.189388,-0.037293,-0.000843,1.339783,-0.056770,laminar,52
4,0.011111,0.789474,0.100000,-0.010775,-0.002226,-6.315435,0.000000,0.000000,0.000000,0.000000,0.179054,0.061017,laminar,62

In [11]:
data_laminar["x"].unique(), data_laminar["y"].unique()

(array([0.36842105, 0.31578947, 0.26315789, 0.05263158, 0.78947368,
        0.73684211, 0.        , 0.89473684, 0.52631579, 0.47368421,
        0.21052632, 0.63157895, 0.94736842, 0.68421053, 0.10526316,
        0.42105263, 0.15789474, 0.57894737, 1.        , 0.84210526]),
 array([0.08888889, 0.07777778, 0.02222222, 0.04444444, 0.1       ,
        0.06666667, 0.03333333, 0.05555556, 0.        , 0.01111111]))

In [12]:
data_laminar = data_laminar.drop(["flow_type", "sample_id"], axis=1)

In [13]:
data_laminar.head()

,t,x,y,u,v,p,dudx,dudy,dvdx,dvdy,dudt,dvdt
0,0.022222,0.368421,0.088889,0.393358,0.001115,-2.953893,0.152946,-31.138013,0.030149,-0.082668,-0.820783,0.018075
1,0.100000,0.315789,0.077778,0.694818,-0.001654,-2.531341,-0.100485,-21.879110,-0.007235,0.056004,-0.027166,-0.151602
2,0.033333,0.263158,0.022222,0.704109,-0.000018,-2.103342,0.178065,23.040452,0.022634,0.011209,0.343724,-0.002956
3,0.100000,0.052632,0.044444,1.002908,-0.001317,-0.410112,-0.151426,4.189388,-0.037293,-0.000843,1.339783,-0.056770
4,0.011111,0.789474,0.100000,-0.010775,-0.002226,-6.315435,0.000000,0.000000,0.000000,0.000000,0.179054,0.061017

In [14]:
data_laminar.to_csv("Laminar_dataset.csv")

In [15]:
data_turbulent = data_turbulent.drop(["flow_type", "sample_id"], axis=1)
data_turbulent.to_csv("Turbulent_dataset.csv")

In [16]:
data_laminar.describe()

,t,x,y,u,v,p,dudx,dudy,dvdx,dvdy,dudt,dvdt
count,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000
mean,0.050573,0.496547,0.050364,0.600999,0.000024,-3.665240,0.000185,-0.114731,0.000172,-0.001845,-0.015610,0.000688
std,0.031246,0.302907,0.031581,0.346460,0.001376,2.551494,0.108610,17.924191,0.015960,0.075724,0.801923,0.081327
min,0.000000,0.000000,0.000000,-0.032690,-0.005760,-8.022295,-0.423242,-32.873241,-0.065424,-0.270811,-4.450283,-0.438851
25%,0.022222,0.210526,0.022222,0.392070,-0.000890,-5.893345,-0.043331,-13.258073,-0.007351,-0.038859,-0.491813,-0.048810
50%,0.055556,0.526316,0.055556,0.691358,-0.000011,-3.780878,0.000000,0.000000,0.000000,0.000000,-0.021671,0.000615
75%,0.077778,0.736842,0.077778,0.894105,0.000953,-1.268140,0.042912,13.207867,0.008029,0.034075,0.472072,0.048247
max,0.100000,1.000000,0.100000,1.018075,0.006097,0.024720,0.487738,33.021308,0.068235,0.445875,3.601717,0.428607

In [ ]:
print(data_laminar["x"] == 0.0)

0       False
1       False
2       False
3       False
4       False
        ...
4995    False
4996    False
4997    False
4998    False
4999    False
Name: x, Length: 5000, dtype: bool